# Generated by Django 5.0.2 on 2024-02-14 12:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Snapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='location',
            name='width',
        ),
    ]
