# Generated by Django 5.0.2 on 2024-02-14 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Snapp', '0002_remove_location_width'),
    ]

    operations = [
        migrations.AddField(
            model_name='location',
            name='width',
            field=models.IntegerField(default=0),
        ),
    ]
