# Generated by Django 5.0.2 on 2024-02-15 14:11

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Snapp', '0004_alter_driver_location_driv'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servise',
            name='registration_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
