# Generated by Django 5.0.2 on 2024-02-17 08:07

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Snapp', '0006_suggesdriver'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service_charge',
            name='date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
