# Generated by Django 4.2.14 on 2024-08-01 08:18

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='License',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('license_key', models.CharField(default='fb4ad53a1abc4b3e9675b4d5c58efd', max_length=30, unique=True)),
                ('created_at', models.DateTimeField(default=datetime.datetime(2024, 8, 1, 8, 18, 31, 36694, tzinfo=datetime.timezone.utc))),
                ('expires_at', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('license', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='license_app.license')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='license_app.user')),
            ],
        ),
        migrations.AddField(
            model_name='license',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='license_app.user'),
        ),
    ]
