# Generated by Django 4.2.14 on 2024-08-01 08:20

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('license_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='license',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='license',
            name='license_key',
            field=models.CharField(default='12a418564dcd4027bfb5108a80c70c', max_length=30, unique=True),
        ),
    ]
