# Generated by Django 5.0.2 on 2024-02-16 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Snapp', '0005_alter_servise_registration_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='SuggesDriver',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_customer', models.CharField(default=0, max_length=250)),
                ('driver_name', models.CharField(default=0, max_length=250)),
                ('spase_driv_custom', models.IntegerField(default=0)),
                ('price_trip', models.IntegerField(default=0)),
                ('end_travel', models.IntegerField(default=0)),
            ],
        ),
    ]
