# Generated by Django 4.2 on 2024-03-11 08:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Snapp', '0009_customer_driver_location_register_a_comment_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdminRestaurant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('admin_name', models.CharField(max_length=20)),
                ('admin_number', models.IntegerField(default=0)),
                ('password', models.CharField(max_length=20)),
            ],
        ),
        migrations.DeleteModel(
            name='Customer',
        ),
        migrations.DeleteModel(
            name='Driver',
        ),
        migrations.DeleteModel(
            name='Location',
        ),
        migrations.DeleteModel(
            name='Register_a_comment',
        ),
        migrations.DeleteModel(
            name='Service_charge',
        ),
        migrations.DeleteModel(
            name='Servise',
        ),
        migrations.DeleteModel(
            name='SnappManager',
        ),
        migrations.DeleteModel(
            name='SuggesDriver',
        ),
        migrations.DeleteModel(
            name='Transaction',
        ),
    ]
