# Generated by Django 4.2 on 2024-03-11 09:59

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('Snapp', '0010_adminrestaurant_delete_customer_delete_driver_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Food',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('food_name', models.CharField(max_length=20)),
                ('customer_name', models.CharField(max_length=20)),
                ('food_price', models.IntegerField(default=0)),
                ('food_code', models.IntegerField(default=0)),
                ('time_reserve', models.CharField(default=django.utils.timezone.now, max_length=20)),
            ],
        ),
    ]
