# Generated by Django 4.2 on 2024-03-11 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Snapp', '0011_food'),
    ]

    operations = [
        migrations.CreateModel(
            name='foods_list',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_food', models.CharField(max_length=30)),
                ('price_foo', models.IntegerField(default=0)),
            ],
        ),
        migrations.RenameModel(
            old_name='Food',
            new_name='Food_reseved',
        ),
    ]
