# Generated by Django 5.0.2 on 2024-02-14 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Snapp', '0003_location_width'),
    ]

    operations = [
        migrations.AlterField(
            model_name='driver',
            name='location_driv',
            field=models.IntegerField(default=0),
        ),
    ]
