# Generated by Django 4.2 on 2024-03-11 08:17

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('Snapp', '0008_adminrestaurant_food_delete_customer_delete_driver_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_code', models.IntegerField(default=0)),
                ('name', models.CharField(max_length=250)),
                ('familly', models.CharField(max_length=250)),
                ('addres', models.CharField(max_length=250)),
                ('phone_number', models.IntegerField(default=0)),
                ('location_driv', models.CharField(default=0, max_length=250)),
                ('wallet_customer', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Driver',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('manager_code', models.CharField(max_length=250)),
                ('driver_code', models.IntegerField(default=0)),
                ('name', models.CharField(max_length=250)),
                ('familly', models.CharField(max_length=250)),
                ('phone_number', models.IntegerField(default=0)),
                ('address', models.CharField(max_length=250)),
                ('national_code', models.IntegerField(default=0)),
                ('model_car', models.CharField(max_length=250)),
                ('color', models.CharField(max_length=250)),
                ('plaque_car', models.IntegerField(default=0)),
                ('location_driv', models.IntegerField(default=0)),
                ('wallet_driver', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lenght', models.IntegerField(default=0)),
                ('width', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Register_a_comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('drive_na', models.CharField(default=0, max_length=250)),
                ('travel_code', models.IntegerField(default=0)),
                ('option', models.CharField(max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='Service_charge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('manager_code', models.CharField(default=0, max_length=250)),
                ('driver_co', models.CharField(default=0, max_length=250)),
                ('service_charg_code', models.IntegerField(default=0)),
                ('date', models.DateTimeField(default=django.utils.timezone.now)),
                ('price', models.IntegerField(default=0)),
                ('tracking_code', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Servise',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('drive_nam', models.CharField(default=0, max_length=250)),
                ('plaq_car', models.CharField(default=0, max_length=250)),
                ('customer_name', models.CharField(default=0, max_length=250)),
                ('location_start', models.IntegerField(default=0)),
                ('location_end', models.IntegerField(default=0)),
                ('price_travel', models.IntegerField(default=0)),
                ('registration_date', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='SnappManager',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.IntegerField()),
                ('name', models.CharField(max_length=250)),
                ('familly', models.CharField(max_length=250)),
                ('addres', models.CharField(max_length=250)),
                ('phone_number', models.IntegerField(default=0)),
                ('user_name', models.CharField(max_length=250)),
                ('password', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='SuggesDriver',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_customer', models.CharField(default=0, max_length=250)),
                ('driver_name', models.CharField(default=0, max_length=250)),
                ('spase_driv_custom', models.IntegerField(default=0)),
                ('price_trip', models.IntegerField(default=0)),
                ('end_travel', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_name', models.CharField(max_length=250)),
                ('transaction_code', models.IntegerField(default=0)),
                ('date', models.DateTimeField(default=django.utils.timezone.now)),
                ('price', models.IntegerField(default=0)),
                ('bank', models.CharField(max_length=250)),
                ('traking_code', models.IntegerField(default=0)),
            ],
        ),
        migrations.DeleteModel(
            name='AdminRestaurant',
        ),
        migrations.DeleteModel(
            name='Food',
        ),
    ]
